### ISSUE TITLE
Missing Reference System.Windows.Forms

### ISSUE THREAD

**Issue by NoxMortem** [gkngkc/UnityStandaloneFileBrowser#25]
![grafik](https://user-images.githubusercontent.com/6750572/34383966-534f3cce-eb19-11e7-9eb7-d40bf073f9bd.png)
For some reason this reference goes missing all the time. I add it again, everything seems to work and shortly after it is gone.

This looks more like some sort of Unity error or related to my IDE but I was still hoping for any help here as I have encountered it only with USFB so far :)

**Comment by gkngkc** [comment]
Thank you for letting me know,

This error usually happens when /Plugins/System.Windows.Forms.dll's import settings are not checked for windows. It should look like [this](https://raw.githubusercontent.com/gkngkc/UnityStandaloneFileBrowser/master/Images/win_import_2.jpg).

But you're saying it goes missing after some time and i heard other people run into this issue. I'm not exactly sure what causing this. Platform switching? Some unity project bug? Or maybe unity get confused when you add a dll from mono to the project.

I'm afraid i can't offer much help but if you find a case when this reference goes, please let me know.

**Comment by NoxMortem** [comment]
Sadly the import settings are checked.
![grafik](https://user-images.githubusercontent.com/6750572/34532252-c482d7ce-f0b5-11e7-95c3-1dd0148c0592.png)

**Comment by NoxMortem** [comment]
@gkngkc Just founds this warning, which likely is related to this?
![grafik](https://user-images.githubusercontent.com/6750572/34584694-1f441d2a-f19d-11e7-866f-b3352a4336d6.png)

Is the standalone file browser not supported on standalonewin64?

**Comment by gkngkc** [comment]
No it's supported. [Here](https://gist.github.com/gkngkc/196bdc264c86f8cc8a85b006e064aa0b#file-gistfile1-txt) is the cloud build log for standalonewindows64 / Unity 2017.3.0f3

I never see this warning before, what is your unity version?

**Comment by NoxMortem** [comment]
I have never seen this warning before as well :). It is Unity 2017.3.0f3

**Comment by XPav** [comment]
I believe this actually showed up with a recent Visual Studio update.    I can't actually debug when this is happening, as the build fails.    Previously with 15.5.2, if I remove the Reference and re-add it, it then builds.     

Interesting notes:  when add the reference, in properties, it lists the path as "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Windows.Forms.dll", rather than the local dll.    

And super oddly, the Visual Studio update released this week (15.5.3) makes my workaround of removing/adding the reference not work.

**Comment by NoxMortem** [comment]
@gkngkc , @XPav working as intended according to Unity. see https://feedback.unity3d.com/suggestions/do-not-remove-references-to-non-net-core-dlls-and-let-us-decide-if-we-want-to-use-them

**Comment by XPav** [comment]
But it doesn't actually remove the reference, it just puts in a... wrong one.  And I don't think it's Unity, I think it's Visual Studio.  Or maybe VS and Unity together.

**Comment by thorgeirk11** [comment]
Please vote on this feature request 🙏 
https://feedback.unity3d.com/suggestions/do-not-remove-references-to-non-net-core-dlls-and-let-us-decide-if-we-want-to-use-them

**Comment by J450NP13** [comment]
This issue is still happening in version 2020.3.1

I wanted to use this git….but it didn’t have the normal save dialogue that Windows has so I went to System.Windows.Forms….worked it the editor but couldn’t build it.

It does work by using this in the project then referencing Windows forms and using the Windows save file dialogue.
