### ISSUE TITLE
How to install the package to Unity project?

### ISSUE THREAD

**Issue by thinium** [gkngkc/UnityStandaloneFileBrowser#81]
Hi I am new to Unity and am trying to add this file browser package to my project.
I tried 2 ways to add the package but failed:
**1. Window->Package Manager -> Add package from disk -> choose "Package/manifest.json"**
Then I get "Please select a valid package.json file in a package folder.
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32) (at /Users/builduser/buildslave/unity/build/Editor/Mono/GUI/GenericMenu.cs:121)"

**2. Window->Package Manager -> "Add package from git URL..."**
I pasted this URL: https://github.com/gkngkc/UnityStandaloneFileBrowser.git 
Then I get this error message:

Cannot perform upm operation: Unable to add package [https://github.com/gkngkc/UnityStandaloneFileBrowser/releases/download/1.2/]:
  Package name 'https://github.com/gkngkc/UnityStandaloneFileBrowser/releases/download/1.2/' is invalid. [InvalidParameter]
UnityEditor.EditorApplication:Internal_CallUpdateFunctions() (at /Users/builduser/buildslave/unity/build/Editor/Mono/EditorApplication.cs:310)

What is the correct way to add this package? Thanks!

**Comment by TheNotary** [comment]
Astonishingly, this unanswered github issue is a top google hit.  Do you happen to recall what the naming constraints are for Unity packages?

**Comment by thinium** [comment]
Thanks for the reply @TheNotary. I don't recall the error anymore. I guess it might had worked at the end (the project is over long time ago).

**Comment by TheNotary** [comment]
Looks like you may have gotten around the issue by adding the project from local hard drive.  It turns out when adding from a github URL, the url you paste in needs to follow this form: 

```https://github.com/TheNotary/org.njax.SimpleWebsocketServer.git``` 

Notice how it ends in `.git` and starts as a reversed domain name which is a common packaging convention in Java (and C#?).  Great writeup on this question, you'd probably make a lot of points if you brought it to Stack Overflow though it probably has just as much reach here.
